// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.appins.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The Domain model. */
@Fluent
public class Domain {
    /*
     * Ignored value.
     */
    @JsonProperty(value = "test")
    private String test;

    /**
     * Get the test property: Ignored value.
     *
     * @return the test value.
     */
    public String getTest() {
        return this.test;
    }

    /**
     * Set the test property: Ignored value.
     *
     * @param test the test value to set.
     * @return the Domain object itself.
     */
    public Domain setTest(String test) {
        this.test = test;
        return this;
    }
}
