// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.appins.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** The EventData model. */
@Fluent
public final class EventData extends Domain {
    /*
     * Schema version
     */
    @JsonProperty(value = "ver", required = true)
    private int ver;

    /*
     * Event name. Keep it low cardinality to allow proper grouping and useful
     * metrics.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /*
     * Collection of custom properties. TODO: max key length validate
     */
    @JsonProperty(value = "properties")
    private Map<String, String> properties;

    /*
     * Collection of custom measurements. TODO: max key length validate
     */
    @JsonProperty(value = "measurements")
    private Map<String, Double> measurements;

    /**
     * Get the ver property: Schema version.
     *
     * @return the ver value.
     */
    public int getVer() {
        return this.ver;
    }

    /**
     * Set the ver property: Schema version.
     *
     * @param ver the ver value to set.
     * @return the EventData object itself.
     */
    public EventData setVer(int ver) {
        this.ver = ver;
        return this;
    }

    /**
     * Get the name property: Event name. Keep it low cardinality to allow proper grouping and useful metrics.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: Event name. Keep it low cardinality to allow proper grouping and useful metrics.
     *
     * @param name the name value to set.
     * @return the EventData object itself.
     */
    public EventData setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the properties property: Collection of custom properties. TODO: max key length validate.
     *
     * @return the properties value.
     */
    public Map<String, String> getProperties() {
        return this.properties;
    }

    /**
     * Set the properties property: Collection of custom properties. TODO: max key length validate.
     *
     * @param properties the properties value to set.
     * @return the EventData object itself.
     */
    public EventData setProperties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the measurements property: Collection of custom measurements. TODO: max key length validate.
     *
     * @return the measurements value.
     */
    public Map<String, Double> getMeasurements() {
        return this.measurements;
    }

    /**
     * Set the measurements property: Collection of custom measurements. TODO: max key length validate.
     *
     * @param measurements the measurements value to set.
     * @return the EventData object itself.
     */
    public EventData setMeasurements(Map<String, Double> measurements) {
        this.measurements = measurements;
        return this;
    }
}
