// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.appins.models;

import com.azure.core.exception.HttpResponseException;
import com.azure.core.http.HttpResponse;

/** Exception thrown for an invalid response with ExceptionData information. */
public final class ExceptionDataException extends HttpResponseException {
    /**
     * Initializes a new instance of the ExceptionDataException class.
     *
     * @param message the exception message or the response content if a message is not available.
     * @param response the HTTP response.
     */
    public ExceptionDataException(String message, HttpResponse response) {
        super(message, response);
    }

    /**
     * Initializes a new instance of the ExceptionDataException class.
     *
     * @param message the exception message or the response content if a message is not available.
     * @param response the HTTP response.
     * @param value the deserialized response value.
     */
    public ExceptionDataException(String message, HttpResponse response, ExceptionData value) {
        super(message, response, value);
    }

    @Override
    public ExceptionData getValue() {
        return (ExceptionData) super.getValue();
    }
}
