// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.appins.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Duration;
import java.util.Map;

/** The PageViewPerfData model. */
@Fluent
public final class PageViewPerfData extends Domain {
    /*
     * Schema version
     */
    @JsonProperty(value = "ver", required = true)
    private int ver;

    /*
     * Identifier of a page view instance. Used for correlation between page
     * view and other telemetry items.
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * Event name. Keep it low cardinality to allow proper grouping and useful
     * metrics.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /*
     * Request URL with all query string parameters
     */
    @JsonProperty(value = "url")
    private String url;

    /*
     * Request duration in format: DD.HH:MM:SS.MMMMMM. For a page view
     * (PageViewData), this is the duration. For a page view with performance
     * information (PageViewPerfData), this is the page load time. Must be less
     * than 1000 days.
     */
    @JsonProperty(value = "duration")
    private Duration duration;

    /*
     * Performance total in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff
     */
    @JsonProperty(value = "perfTotal")
    private Duration perfTotal;

    /*
     * Network connection time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff
     */
    @JsonProperty(value = "networkConnect")
    private Duration networkConnect;

    /*
     * Sent request time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff
     */
    @JsonProperty(value = "sentRequest")
    private Duration sentRequest;

    /*
     * Received response time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff
     */
    @JsonProperty(value = "receivedResponse")
    private Duration receivedResponse;

    /*
     * DOM processing time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff
     */
    @JsonProperty(value = "domProcessing")
    private Duration domProcessing;

    /*
     * Collection of custom properties. TODO: max key length validate
     */
    @JsonProperty(value = "properties")
    private Map<String, String> properties;

    /*
     * Collection of custom measurements. TODO: max key length validate
     */
    @JsonProperty(value = "measurements")
    private Map<String, Double> measurements;

    /**
     * Get the ver property: Schema version.
     *
     * @return the ver value.
     */
    public int getVer() {
        return this.ver;
    }

    /**
     * Set the ver property: Schema version.
     *
     * @param ver the ver value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setVer(int ver) {
        this.ver = ver;
        return this;
    }

    /**
     * Get the id property: Identifier of a page view instance. Used for correlation between page view and other
     * telemetry items.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id property: Identifier of a page view instance. Used for correlation between page view and other
     * telemetry items.
     *
     * @param id the id value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name property: Event name. Keep it low cardinality to allow proper grouping and useful metrics.
     *
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: Event name. Keep it low cardinality to allow proper grouping and useful metrics.
     *
     * @param name the name value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the url property: Request URL with all query string parameters.
     *
     * @return the url value.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Set the url property: Request URL with all query string parameters.
     *
     * @param url the url value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get the duration property: Request duration in format: DD.HH:MM:SS.MMMMMM. For a page view (PageViewData), this
     * is the duration. For a page view with performance information (PageViewPerfData), this is the page load time.
     * Must be less than 1000 days.
     *
     * @return the duration value.
     */
    public Duration getDuration() {
        return this.duration;
    }

    /**
     * Set the duration property: Request duration in format: DD.HH:MM:SS.MMMMMM. For a page view (PageViewData), this
     * is the duration. For a page view with performance information (PageViewPerfData), this is the page load time.
     * Must be less than 1000 days.
     *
     * @param duration the duration value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setDuration(Duration duration) {
        this.duration = duration;
        return this;
    }

    /**
     * Get the perfTotal property: Performance total in TimeSpan 'G' (general long) format: d:hh:mm:ss.fffffff.
     *
     * @return the perfTotal value.
     */
    public Duration getPerfTotal() {
        return this.perfTotal;
    }

    /**
     * Set the perfTotal property: Performance total in TimeSpan 'G' (general long) format: d:hh:mm:ss.fffffff.
     *
     * @param perfTotal the perfTotal value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setPerfTotal(Duration perfTotal) {
        this.perfTotal = perfTotal;
        return this;
    }

    /**
     * Get the networkConnect property: Network connection time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff.
     *
     * @return the networkConnect value.
     */
    public Duration getNetworkConnect() {
        return this.networkConnect;
    }

    /**
     * Set the networkConnect property: Network connection time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff.
     *
     * @param networkConnect the networkConnect value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setNetworkConnect(Duration networkConnect) {
        this.networkConnect = networkConnect;
        return this;
    }

    /**
     * Get the sentRequest property: Sent request time in TimeSpan 'G' (general long) format: d:hh:mm:ss.fffffff.
     *
     * @return the sentRequest value.
     */
    public Duration getSentRequest() {
        return this.sentRequest;
    }

    /**
     * Set the sentRequest property: Sent request time in TimeSpan 'G' (general long) format: d:hh:mm:ss.fffffff.
     *
     * @param sentRequest the sentRequest value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setSentRequest(Duration sentRequest) {
        this.sentRequest = sentRequest;
        return this;
    }

    /**
     * Get the receivedResponse property: Received response time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff.
     *
     * @return the receivedResponse value.
     */
    public Duration getReceivedResponse() {
        return this.receivedResponse;
    }

    /**
     * Set the receivedResponse property: Received response time in TimeSpan 'G' (general long) format:
     * d:hh:mm:ss.fffffff.
     *
     * @param receivedResponse the receivedResponse value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setReceivedResponse(Duration receivedResponse) {
        this.receivedResponse = receivedResponse;
        return this;
    }

    /**
     * Get the domProcessing property: DOM processing time in TimeSpan 'G' (general long) format: d:hh:mm:ss.fffffff.
     *
     * @return the domProcessing value.
     */
    public Duration getDomProcessing() {
        return this.domProcessing;
    }

    /**
     * Set the domProcessing property: DOM processing time in TimeSpan 'G' (general long) format: d:hh:mm:ss.fffffff.
     *
     * @param domProcessing the domProcessing value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setDomProcessing(Duration domProcessing) {
        this.domProcessing = domProcessing;
        return this;
    }

    /**
     * Get the properties property: Collection of custom properties. TODO: max key length validate.
     *
     * @return the properties value.
     */
    public Map<String, String> getProperties() {
        return this.properties;
    }

    /**
     * Set the properties property: Collection of custom properties. TODO: max key length validate.
     *
     * @param properties the properties value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setProperties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the measurements property: Collection of custom measurements. TODO: max key length validate.
     *
     * @return the measurements value.
     */
    public Map<String, Double> getMeasurements() {
        return this.measurements;
    }

    /**
     * Set the measurements property: Collection of custom measurements. TODO: max key length validate.
     *
     * @param measurements the measurements value to set.
     * @return the PageViewPerfData object itself.
     */
    public PageViewPerfData setMeasurements(Map<String, Double> measurements) {
        this.measurements = measurements;
        return this;
    }
}
